### ISSUE TITLE
Delete user endpoint broken

### ISSUE THREAD

**Issue by IIIuminator** [BjoernPetersen/MusicBot-desktop#48]
Querying `DELETE /user` with Token auth results in an auth expectation for Basic, querying with Basic results in one saying Token. [API](https://74-92969231-gh.circle-artifacts.com/0/docs/index.html?circle-token=46dc7aefa69e32721cbdf9ec6e74645f52055c13#deleteUser) says a token is required

**Comment by IIIuminator** [comment]
Querying with both types results in an AuthExpectation with the type that was added to the head last i.e. the server seems to check the first type and then stop.

**Comment by BjoernPetersen** [comment]
The HTML doc doesn't do a great job reflecting the required auth here. According to the actual spec file, either Basic or Token can be used. The problem lies within Vertx, which doesn't handle that correctly and requires both security requirements to be satisifed, which obviously isn't possible.

See also https://github.com/vert-x3/vertx-web/issues/1036

**Comment by BjoernPetersen** [comment]
I'm just going to accept that this is broken until Vertx 4.0.0 is released.

**Comment by BjoernPetersen** [comment]
Fixed by only accepting Basic auth in a975968d5d0ac84f9a2ee4c6a99f2b4fd548c06b
